### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by emilianobonassi** [AsafSilman/idle-smart-treasury#11]
Thank you @AsafSilman for the time dedicated to this important contribution for IdleFinance!

Overall the code is good, `SmartTreasuryBootstrap` has good quality instead `FeeCollector` could be improved.

The most important finding (but not critical) is that `FeeCollector` swaps fees with no slippage control at

https://github.com/AsafSilman/idle-smart-treasury/blob/main/contracts/FeeCollector.sol#L220

For `SmartTreasuryBootstrap` it could be useful to track the status of the initialization via an enum state (e.g. an int could suffice), to avoid errors during the initial process. Also if this is executed by a trusted party.

To be checked the withdraw part, comments does not reflect implementation

https://github.com/AsafSilman/idle-smart-treasury/blob/main/contracts/SmartTreasuryBootstrap.sol#L268-L280 

From operational perspective, use Taichi for executing swap txs (especially initial one) to avoid sandwiches attacks!

Consider also consistent naming for public and internal methods. A linter could be useful. Sometimes spaces are not consistent.

Below my other comments. (Per contract and per method).

### SmartTreasuryBootstrap

**Constructor**

1. Consider to use a smart contract which extends the current one with the values already set for mainnet. It can be tested and avoid last time deploy issues.

2. Declare a var instead of access more times. 

https://github.com/AsafSilman/idle-smart-treasury/blob/main/contracts/SmartTreasuryBootstrap.sol#L99

3. Consider to use use type(uint256).max

https://github.com/AsafSilman/idle-smart-treasury/blob/main/contracts/SmartTreasuryBootstrap.sol#L101

**Swap**

1. Add a threshold 1800 i.e. block.timestamp.add(1800), there are cases swap could fail.

https://github.com/AsafSilman/idle-smart-treasury/blob/main/contracts/SmartTreasuryBootstrap.sol#L136

**SetIdlePrice**

OK

**Initialize**

1. What's the rationale? Some min value? Thanks!

https://github.com/AsafSilman/idle-smart-treasury/blob/main/contracts/SmartTreasuryBootstrap.sol#L155-L156

2. Fix comments. idle/total and weth/total 

https://github.com/AsafSilman/idle-smart-treasury/blob/main/contracts/SmartTreasuryBootstrap.sol#L173-L174

3. What's the purpose of this check? Thanks!

https://github.com/AsafSilman/idle-smart-treasury/blob/main/contracts/SmartTreasuryBootstrap.sol#L176

**BootStrap**

OK

**Withdraw**

1. Comment is not correct or not implemented the expected behaviour. It withdraws from the current contract not feeCollector.

https://github.com/AsafSilman/idle-smart-treasury/blob/main/contracts/SmartTreasuryBootstrap.sol#L268-L280

### FeeCollector

**Constructor**

1. Consider to use a smart contract which extends the current one with the values already set for mainnet. It can be tested and avoid deploy errors.

2. Declare a var instead of access two times.  
https://github.com/AsafSilman/idle-smart-treasury/blob/main/contracts/FeeCollector.sol#L101

3. Consider to use use type(uint256).max
https://github.com/AsafSilman/idle-smart-treasury/blob/main/contracts/FeeCollector.sol#L103

**Deposit**

1. Declaration not needed.
https://github.com/AsafSilman/idle-smart-treasury/blob/main/contracts/FeeCollector.sol#L134-L136

2. Add a threshold 1800 i.e. block.timestamp.add(1800), there are cases swap could fail.
https://github.com/AsafSilman/idle-smart-treasury/blob/main/contracts/FeeCollector.sol#L150

**_amountsFromAllocation**

1. Avoid check everytime, refactor line 399 outside the for and limit the iteration to -1.

https://github.com/AsafSilman/idle-smart-treasury/blob/main/contracts/FeeCollector.sol#L392-L407

2. Better to use a tuple instead of an array to be more explicit between beneficiaries and smartTreasurySet.

https://github.com/AsafSilman/idle-smart-treasury/blob/main/contracts/FeeCollector.sol#L165

https://github.com/AsafSilman/idle-smart-treasury/blob/main/contracts/FeeCollector.sol#L172

**_setSplitAllocations**

OK

**_depositAllTokens**

1. No slippage protection, it's set to 1.

https://github.com/AsafSilman/idle-smart-treasury/blob/main/contracts/FeeCollector.sol#L220

2. Internal calls public, re-define deposit to call an internal function and move implementation there.

https://github.com/AsafSilman/idle-smart-treasury/blob/main/contracts/FeeCollector.sol#L223

**addBeneficiaryAddress**

OK

**removeBeneficiaryAt(uint256 _index, uint256[] calldata _newAllocation)**

1. Missing check on index max value. You can empty the array by error.

https://github.com/AsafSilman/idle-smart-treasury/blob/main/contracts/FeeCollector.sol#L266

**replaceBeneficiaryAt(uint256 _index, address _newBeneficiary, uint256[] calldata _newAllocation)**

OK

**setSmartTreasuryAddress**

1. Consider to use use type(uint256).max

https://github.com/AsafSilman/idle-smart-treasury/blob/main/contracts/FeeCollector.sol#L317

**addAddressToWhiteList**

OK

**removeAddressFromWhiteList**

OK

**registerTokenToDepositList**

1. Consider to use use type(uint256).max

https://github.com/AsafSilman/idle-smart-treasury/blob/main/contracts/FeeCollector.sol#L356

**removeTokenFromDepositList**

OK

**withdraw**

1. Unneeded definition

https://github.com/AsafSilman/idle-smart-treasury/blob/main/contracts/FeeCollector.sol#L379

**withdrawUnderlying**

1. Unneeded definition. Calculate difference and then safeTransfer only if > 0.

https://github.com/AsafSilman/idle-smart-treasury/blob/main/contracts/FeeCollector.sol#L435-L443

**Comment by AsafSilman** [comment]
Hi Emiliano 👋 

Thank you for all your feedback in this review.

I have fixed up all the comment issues you have raised, and the code optimisation suggestions regarding variable declarations. Also the issue swaping timestamp thresholds.

Regarding the deployment to mainnet I have a set of migration scripts which have all these parameters encoded which reduces the risk of missing parameters at deploy-time.

Regarding the no slippage behaviour for `_depositAllTokens` which is called in `setSplitAllocation`, `[add|remove|replace]beneficiary` are all functions which need to be called by the contract admin, which will be delegated to the idle timelock (governance). The turn-around for governance to go from proposal to executable code is 3 days, which means it will be difficult to set reasonable slippage parameters without risking the proposal failing. The risk for slippage increases if the balance in the feeCollector becomes too high, which is why to minimise this risk, the whitelisted account should call `deposit` before such a proposal is executed to minimise the potential slippage.

Regarding `_amountsFromAllocation`, I've implemented your suggestion for reducing the check each iteration, however, making the return value a tuple IMO makes this function too overloaded, so I won't be making this change. To make the code clearer I will add a variable in `_deposit` for `feeBalances[0]` called `smartTreasuryFee`.

Regarding `Initialize` for the **SmartTreasuryBootstrap**, the rationale behind the first check was indeed to check that there was some minimum balance in the contract, though I've changes this value now to be slightly higher `1 ETH`, and `100 IDLE`, as a sanity check. The second check was a recommendation from the balancer review here https://github.com/AsafSilman/idle-smart-treasury/issues/7
