### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by MickdeGraaf** [AsafSilman/idle-smart-treasury#12]
The contracts look good, some small points:

## FeeCollector

**Unneeded functions for adding from and to the whitelist**

Since the ``FeeCollector`` uses the ``AccesControl`` contract from Openzeppelin the ``addAddressToWhiteList`` and ``removeAddressFromWhiteList `` could be removed in favour of using the build in ``roleAdmin`` functionality of the AccesControl contract. This can be done by calling ``_setRoleAdmin(WHITELISTED, DEFAULT_ADMIN_ROLE)`` in the constructor.

**Unneeded changeAdmin**

The same as the not mentioned above could be applied to the ``replaceAdmin`` function by assigning the role admin in the constructor.

**Possible duplicate beneficiaries**

``addBeneficiaryAddress`` Does not check for the same address to be added twice. Although not strictly necessary it might make sense to ensure all entries are unique

## SmartTreasuryBootstrap

**swap**

In swap you could declare ``counter`` at the start of the function and then use that in the ``require`` statement to check the array lengths to possibly save 1 storage load (Optimizer might do this already).

**initialise**

Could you clarify these calculations? I'm not sure what you are trying to achieve

https://github.com/AsafSilman/idle-smart-treasury/blob/main/contracts/SmartTreasuryBootstrap.sol#L172-L176

Overall I could not find any critical or major flaws. Well done!

**Comment by AsafSilman** [comment]
Hi @MickdeGraaf,

Thank you for your feedback, regarding the FeeCollector, you are correct regarding the whitelist; this true, and I could technically remove these functions for the contract. However, I have decided to keep them in as convenience functions for future governance. 

regarding `replaceAdmin` I follow the same logic as before, in addition, for this function it helps to keep the call down to 1 instead of 2 calls which governance would have to make otherwise. It also ensures that the ordering is correct. It would be erroneous to call `revokeRole` then `grantRole`. (you can no longer grant after you have revoked).

I've implemented the **swap** optimisation for the smart treasury bootstrap.

Regarding the calculations, please refer to this issue https://github.com/AsafSilman/idle-smart-treasury/issues/7
